name: Build distribution 📦
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and pthon
        uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: uv sync
      - name: Build distribution
        run: uv build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
